### ISSUE TITLE
interaction select not working with :features prop after 0.1.70

### ISSUE THREAD

**Issue by dejvlamm** [MelihAltintas/vue3-openlayers#175] opened 2023-04-13 14:51 UTC
**Describe the bug**

Features added to vector source with prop `:features` are not selectable with `ol-interaction-select` anymore.
@Select does not fire, SelectionInteractionFilter does not fire either.

Events still fire for features added through `:url` prop and `ol-feature`

**To Reproduce**
I create a new and empty repo.
`npm init vue@latest` (3.2.47 with vite)
I`npm install vue3-openlayers` (0.1.75)
I set up main.js:
`import { createApp } from "vue";`
`import App from "./App.vue";`
`import OpenLayersMap from "vue3-openlayers";`
`import "./assets/main.css";`

`const app = createApp(App);`
`app.use(OpenLayersMap);`
`app.mount("#app");`

I copy example code from:
https://vue3openlayers.netlify.app/componentsguide/interactions/modify/

I run `npm run dev`

The features are not selected when clicked.

If I roll back "vue3-openlayers" to version 0.1.70 they become selected when clicked.
The example works in the vue3-openlayers repo, but it does not work in a new clean repo.

**Expected behavior**
They should be selected as in previous versions.

**Comment by dejvlamm** [comment] 2023-04-13 18:36
In addition, if I use the draw interaction to add new features, the new features can be selected.

**Comment by d-koppenhagen** [comment] 2023-04-14 06:22
First investigation:
The problem was introduced with this change:
https://github.com/MelihAltintas/vue3-openlayers/compare/eb300feeecb9d1b6747857568af47b8bdea5a8d2..36d8c71cb54dd7446dc7e4bc365ff628796ff57c

Is can be reproduced by increasing from version `0.1.71` to `0.1.72`.
I provided a Stackblitz project for reproduction:
https://stackblitz.com/edit/vue3-openlayers-interaction-select-features?file=src%2Fcomponents%2FTheMap.vue,package.json

**Comment by d-koppenhagen** [comment] 2023-04-14 06:56
Mir first though was, the update of `ol` to major version `7.x.x` introduced this problem but actually it seems not to be the problem as installing it in version `6.14.1` as before, won't fix the problem.

**Comment by d-koppenhagen** [comment] 2023-04-14 08:50
Locally I could reproduce the problem when updating from `ol@6.15.1` to `ol@7.0.0` and connecting `vue3-openlayers` via `npm link`. So it seems the Major version introduced a breaking change. I will keep on investigation.

**Comment by dejvlamm** [comment] 2023-04-14 21:57
Great work so far, looking forward to your findings. It is puzzling that the example works in the project repo but not in the dist.

**Comment by d-koppenhagen** [comment] 2023-04-15 12:40
It is indeed really strange. Currently I have no Idea how to solve it :/ ... @MelihAltintas do you have any clue what could be the problem?

**Comment by d-koppenhagen** [comment] 2023-05-15 08:24
Not from my site, sorry. I wasn't able to find the root-cause here. I can't guarantee you, I am able to investigate this further within the next weeks.

**Comment by dejvlamm** [comment] 2023-05-15 20:36
> Not from my site, sorry. I wasn't able to find the root-cause here. I can't guarantee you, I am able to investigate this further within the next weeks.

I understand, not even if we put a bounty on it? :)

**Comment by Donchurru** [comment] 2023-05-30 22:19
Hi all, any news on this? I have the same problem.
Thank you in advance

**Comment by d-koppenhagen** [comment] 2023-07-06 21:31
I opened a discussion in the Openlayers repo: https://github.com/openlayers/openlayers/discussions/14885

**Comment by mathiash98** [comment] 2023-07-10 23:13
Note: I have never used openlayers or vue3-openlayers in anything else than testing

I performed quite an extensive debugging on this case:

Methodology:
- Spin up the working docs source code
- Spin up the code in `SnapModifyDemo.vue` locally with NPM as package source
- Serve both on my pc
- Open both pages in Edge side by side
- Add debugger breakpoints in Chromium debugger on every step during handling of click events

Findings:
- When checking if the feature at pixel is instanceof feature, we get true in the source code repo, BUT false in the distributed (npm) source code. See screenshot below for comparison.

<img width="1750" alt="image" src="https://github.com/MelihAltintas/vue3-openlayers/assets/5204006/9a8c58e8-3ab2-42cb-8b93-c28af40f31b7">
- Left is docs source code served locally
- Right is the same code as `SnapModifyDemo.vue` but using the NPM package as source
- I have the same breakpoints
- Observe that the NPM package evaluates `feature$1 instanceof feature` to false such that the next step is `return;` while the left evaluates it to true and checks `!this.filter_(...)`


Suspected root cause on why:
- I have seen similar issues while using vue-leaflet, see https://github.com/vue-leaflet/vue-leaflet/issues/48 . In this case the error occurs when an user creates a LatLng object and passes it into the library. The code will then try to check if the argument is of type LatLng, like OpenLayers does in this case.
- So it seems like the dist source code is building a Feature type based on another import of OpenLayers than what is used during selectionChecking.


How to solve? -> I don't know.

**Closed** 2023-07-11 06:15 UTC
Labels: bug, help wanted

**Comment by Donchurru** [comment] 2023-07-11 08:13
Thank you so much!

When will it be available to install from npm?

Thanks again.

**Comment by mathiash98** [comment] 2023-07-11 08:24
> Thank you so much!
> 
> When will it be available to install from npm?
> 
> Thanks again.

I see @d-koppenhagen is working on something, it should already be available in release `1.0.0-next.9`

**Comment by d-koppenhagen** [comment] 2023-07-11 08:40
Yes, it's already available. Please give some Feedback, I plan to release the stable `1.0.0` version within the next days.

**Comment by Donchurru** [comment] 2023-07-11 09:23
Ok Thanks.
I have downloaded that version and it works!

In that version (1.0.0-next.9) I had to install ol-contextmenu@^5.2.1 because otherwise it wouldn't compile

**Comment by d-koppenhagen** [comment] 2023-07-11 11:15
yes, that's indeed the case. I am thinking about how to make this optional.
